apiVersion: v1
kind: Pod
metadata:
  name: node
spec:
  containers:
  - name: node-server
    image: kazuki728/sample-node:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
